# Generated by Django 3.2 on 2021-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
